[project]
name = "python-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pyqt6>=6.9.1",
    "pythtb>=1.8.0",
    "scipy>=1.15.3",
]
